template_name: base
entities:
  - Data:
      components:
        Tag: world
        CompositeRenderable: None
        CompositeTransform:
          translation:
            x: 224
            y: 224
        CompositeSprite:
          sheet_frame:
            - "sprites.0.json"
            - "base_0.png"
        CompositeSpriteAnimation:
          animations:
            close:
              sheet: "sprites.0.json"
              frames:
                - "base_0.png"
            opening:
              sheet: "sprites.0.json"
              frames:
                - "base_1.png"
            open:
              sheet: "sprites.0.json"
              frames:
                - "base_2.png"    
        InteractiveSprite:
          size: 32
        CompositeRenderDepth: 3