template_name: base
entities:
  - Data:
      components:
        Tag: world
        CompositeRenderable: None
        CompositeTransform:
          translation:
            x: 160
            y: 160
        CompositeRenderDepth: 1
        CompositeSprite:
          sheet_frame:
            - "sprites.0.json"
            - "base.png"
        InteractiveSprite:
          size: 32