template_name: base
entities:
  - Data:
      components:
        Tag: world
        CompositeRenderable: None
        CompositeTransform:
          translation:
            x: 48
            y: 48
        CompositeSprite:
          sheet_frame:
            - "sprites.0.json"
            - "base_0.png" 
        InteractiveSprite:
          w: 48
          h: 64
          code: "base"
        CompositeRenderDepth: 1