template_name: base
entities:
  - Data:
      components:
        Tag: world
        CompositeRenderable: None
        CompositeTransform:
          translation:
            x: 32
            y: 32
        CompositeSprite:
          sheet_frame:
            - "sprites.0.json"
            - "base_0.png" 
        InteractiveSprite:
          w: 32
          h: 48
          code: Base
        CompositeRenderDepth: 1